Fix a bug in date hierarchy month/year
arx-deidentifier/arx pull request #372
Opened 2021-12-13 10:54 UTC by idhamari

Fix Arx [issue 366](https://github.com/arx-deidentifier/arx/issues/366).

2021-12-15 18:44 UTC, prasser requested changes

2021-12-15 18:44 UTC, prasser commented on src/main/org/deidentifier/arx/aggregates/HierarchyBuilderDate.java
> +            String outputDate = "[" + lower + "-" + upper + "]";
The return format [1-3] breaks with the old format which would be [1, 4[. Please adjust. Line 540 can remain unchanged. line 539 should be rewritten as upper    = lower + _range;

2021-12-16 13:58 UTC, idhamari commented
@prasser code is updated!

2021-12-22 15:23 UTC, merged

2021-12-24 13:37 UTC, prasser commented
Just for the record: this change as well as as PR #372 is not correct. The problem is that year (basis for decade, millennium etc.) is 0-based but month (basis for quarter) is 1-based. Hence, different offsets are needed when calculating intervals and the current code is wrong for decades, millennia etc. This has been fixed in the following commit: https://github.com/arx-deidentifier/arx/commit/e1d20d68e1fcabb53fa127286ff1c3ea91c6717b